/**
 * Pre-built system design templates for the builder canvas.
 * Each template defines nodes and edges that create a complete architecture.
 */
export const ARCHITECTURE_TEMPLATES = [
  {
    id: 'web-app',
    name: 'Web Application',
    description: 'Classic 3-tier web app with load balancer, app servers, and database.',
    category: 'Common',
    icon: 'globe',
    nodes: [
      { id: 'tpl-web-1', name: 'Web Client', icon: 'monitor', category: 'Clients', x: 340, y: 30 },
      { id: 'tpl-web-2', name: 'CDN', icon: 'globe', category: 'Storage', x: 540, y: 30 },
      { id: 'tpl-web-3', name: 'Load Balancer', icon: 'split', category: 'Compute', x: 340, y: 140 },
      { id: 'tpl-web-4', name: 'App Server', icon: 'box', category: 'Compute', x: 200, y: 260 },
      { id: 'tpl-web-5', name: 'App Server', icon: 'box', category: 'Compute', x: 480, y: 260 },
      { id: 'tpl-web-6', name: 'Cache (Redis)', icon: 'zap', category: 'Storage', x: 60, y: 380 },
      { id: 'tpl-web-7', name: 'SQL Database', icon: 'database', category: 'Storage', x: 340, y: 380 },
      { id: 'tpl-web-8', name: 'Object Storage', icon: 'archive', category: 'Storage', x: 600, y: 380 },
    ],
    edges: [
      { id: 'te-1', from: 'tpl-web-1', fromAnchor: 'bottom', to: 'tpl-web-3', toAnchor: 'top' },
      { id: 'te-2', from: 'tpl-web-3', fromAnchor: 'bottom', to: 'tpl-web-4', toAnchor: 'top' },
      { id: 'te-3', from: 'tpl-web-3', fromAnchor: 'bottom', to: 'tpl-web-5', toAnchor: 'top' },
      { id: 'te-4', from: 'tpl-web-4', fromAnchor: 'bottom', to: 'tpl-web-6', toAnchor: 'top' },
      { id: 'te-5', from: 'tpl-web-4', fromAnchor: 'bottom', to: 'tpl-web-7', toAnchor: 'top' },
      { id: 'te-6', from: 'tpl-web-5', fromAnchor: 'bottom', to: 'tpl-web-7', toAnchor: 'top' },
      { id: 'te-7', from: 'tpl-web-5', fromAnchor: 'bottom', to: 'tpl-web-8', toAnchor: 'top' },
      { id: 'te-8', from: 'tpl-web-1', fromAnchor: 'right', to: 'tpl-web-2', toAnchor: 'left' },
    ],
  },
  {
    id: 'microservices',
    name: 'Microservices',
    description: 'API gateway with multiple microservices, message queue, and databases.',
    category: 'Common',
    icon: 'box',
    nodes: [
      { id: 'tpl-ms-1', name: 'Mobile Client', icon: 'smartphone', category: 'Clients', x: 200, y: 20 },
      { id: 'tpl-ms-2', name: 'Web Client', icon: 'monitor', category: 'Clients', x: 440, y: 20 },
      { id: 'tpl-ms-3', name: 'API Gateway', icon: 'door-open', category: 'Compute', x: 320, y: 130 },
      { id: 'tpl-ms-4', name: 'Auth Service', icon: 'box', category: 'Compute', x: 80, y: 250 },
      { id: 'tpl-ms-5', name: 'User Service', icon: 'box', category: 'Compute', x: 280, y: 250 },
      { id: 'tpl-ms-6', name: 'Order Service', icon: 'box', category: 'Compute', x: 480, y: 250 },
      { id: 'tpl-ms-7', name: 'Message Queue', icon: 'mail', category: 'Compute', x: 280, y: 380 },
      { id: 'tpl-ms-8', name: 'SQL Database', icon: 'database', category: 'Storage', x: 80, y: 380 },
      { id: 'tpl-ms-9', name: 'NoSQL Database', icon: 'hard-drive', category: 'Storage', x: 480, y: 380 },
      { id: 'tpl-ms-10', name: 'Background Worker', icon: 'cog', category: 'Compute', x: 280, y: 500 },
    ],
    edges: [
      { id: 'tme-1', from: 'tpl-ms-1', fromAnchor: 'bottom', to: 'tpl-ms-3', toAnchor: 'top' },
      { id: 'tme-2', from: 'tpl-ms-2', fromAnchor: 'bottom', to: 'tpl-ms-3', toAnchor: 'top' },
      { id: 'tme-3', from: 'tpl-ms-3', fromAnchor: 'bottom', to: 'tpl-ms-4', toAnchor: 'top' },
      { id: 'tme-4', from: 'tpl-ms-3', fromAnchor: 'bottom', to: 'tpl-ms-5', toAnchor: 'top' },
      { id: 'tme-5', from: 'tpl-ms-3', fromAnchor: 'bottom', to: 'tpl-ms-6', toAnchor: 'top' },
      { id: 'tme-6', from: 'tpl-ms-5', fromAnchor: 'bottom', to: 'tpl-ms-7', toAnchor: 'top' },
      { id: 'tme-7', from: 'tpl-ms-6', fromAnchor: 'bottom', to: 'tpl-ms-9', toAnchor: 'top' },
      { id: 'tme-8', from: 'tpl-ms-4', fromAnchor: 'bottom', to: 'tpl-ms-8', toAnchor: 'top' },
      { id: 'tme-9', from: 'tpl-ms-7', fromAnchor: 'bottom', to: 'tpl-ms-10', toAnchor: 'top' },
    ],
  },
  {
    id: 'event-driven',
    name: 'Event-Driven',
    description: 'Event sourcing architecture with stream processor and analytics.',
    category: 'Advanced',
    icon: 'activity',
    nodes: [
      { id: 'tpl-ev-1', name: 'Web Client', icon: 'monitor', category: 'Clients', x: 80, y: 30 },
      { id: 'tpl-ev-2', name: 'IoT Device', icon: 'cpu', category: 'Clients', x: 340, y: 30 },
      { id: 'tpl-ev-3', name: 'API Gateway', icon: 'door-open', category: 'Compute', x: 200, y: 140 },
      { id: 'tpl-ev-4', name: 'Event Bus', icon: 'radio', category: 'Compute', x: 200, y: 260 },
      { id: 'tpl-ev-5', name: 'Stream Processor', icon: 'activity', category: 'Compute', x: 400, y: 260 },
      { id: 'tpl-ev-6', name: 'Microservice', icon: 'box', category: 'Compute', x: 60, y: 380 },
      { id: 'tpl-ev-7', name: 'NoSQL Database', icon: 'hard-drive', category: 'Storage', x: 200, y: 380 },
      { id: 'tpl-ev-8', name: 'Search Index', icon: 'search', category: 'Storage', x: 400, y: 380 },
      { id: 'tpl-ev-9', name: 'Metrics Collector', icon: 'bar-chart', category: 'Observability', x: 560, y: 260 },
    ],
    edges: [
      { id: 'tee-1', from: 'tpl-ev-1', fromAnchor: 'bottom', to: 'tpl-ev-3', toAnchor: 'top' },
      { id: 'tee-2', from: 'tpl-ev-2', fromAnchor: 'bottom', to: 'tpl-ev-3', toAnchor: 'top' },
      { id: 'tee-3', from: 'tpl-ev-3', fromAnchor: 'bottom', to: 'tpl-ev-4', toAnchor: 'top' },
      { id: 'tee-4', from: 'tpl-ev-4', fromAnchor: 'right', to: 'tpl-ev-5', toAnchor: 'left' },
      { id: 'tee-5', from: 'tpl-ev-4', fromAnchor: 'bottom', to: 'tpl-ev-6', toAnchor: 'top' },
      { id: 'tee-6', from: 'tpl-ev-4', fromAnchor: 'bottom', to: 'tpl-ev-7', toAnchor: 'top' },
      { id: 'tee-7', from: 'tpl-ev-5', fromAnchor: 'bottom', to: 'tpl-ev-8', toAnchor: 'top' },
      { id: 'tee-8', from: 'tpl-ev-5', fromAnchor: 'right', to: 'tpl-ev-9', toAnchor: 'left' },
    ],
  },
  {
    id: 'chat-system',
    name: 'Real-Time Chat',
    description: 'WebSocket-based chat with presence, message history, and notifications.',
    category: 'Interview',
    icon: 'radio',
    nodes: [
      { id: 'tpl-ch-1', name: 'Mobile Client', icon: 'smartphone', category: 'Clients', x: 120, y: 20 },
      { id: 'tpl-ch-2', name: 'Web Client', icon: 'monitor', category: 'Clients', x: 380, y: 20 },
      { id: 'tpl-ch-3', name: 'Load Balancer', icon: 'split', category: 'Compute', x: 250, y: 130 },
      { id: 'tpl-ch-4', name: 'Chat Server', icon: 'box', category: 'Compute', x: 100, y: 250 },
      { id: 'tpl-ch-5', name: 'Presence Server', icon: 'box', category: 'Compute', x: 400, y: 250 },
      { id: 'tpl-ch-6', name: 'Message Queue', icon: 'mail', category: 'Compute', x: 250, y: 370 },
      { id: 'tpl-ch-7', name: 'Cache (Redis)', icon: 'zap', category: 'Storage', x: 400, y: 370 },
      { id: 'tpl-ch-8', name: 'NoSQL Database', icon: 'hard-drive', category: 'Storage', x: 100, y: 480 },
      { id: 'tpl-ch-9', name: 'Background Worker', icon: 'cog', category: 'Compute', x: 400, y: 480 },
    ],
    edges: [
      { id: 'tce-1', from: 'tpl-ch-1', fromAnchor: 'bottom', to: 'tpl-ch-3', toAnchor: 'top' },
      { id: 'tce-2', from: 'tpl-ch-2', fromAnchor: 'bottom', to: 'tpl-ch-3', toAnchor: 'top' },
      { id: 'tce-3', from: 'tpl-ch-3', fromAnchor: 'bottom', to: 'tpl-ch-4', toAnchor: 'top' },
      { id: 'tce-4', from: 'tpl-ch-3', fromAnchor: 'bottom', to: 'tpl-ch-5', toAnchor: 'top' },
      { id: 'tce-5', from: 'tpl-ch-4', fromAnchor: 'bottom', to: 'tpl-ch-6', toAnchor: 'top' },
      { id: 'tce-6', from: 'tpl-ch-5', fromAnchor: 'bottom', to: 'tpl-ch-7', toAnchor: 'top' },
      { id: 'tce-7', from: 'tpl-ch-6', fromAnchor: 'bottom', to: 'tpl-ch-8', toAnchor: 'top' },
      { id: 'tce-8', from: 'tpl-ch-7', fromAnchor: 'bottom', to: 'tpl-ch-9', toAnchor: 'top' },
    ],
  },
  {
    id: 'url-shortener',
    name: 'URL Shortener',
    description: 'High-read system with caching, analytics, and redirect service.',
    category: 'Interview',
    icon: 'external-link',
    nodes: [
      { id: 'tpl-url-1', name: 'Web Client', icon: 'monitor', category: 'Clients', x: 280, y: 20 },
      { id: 'tpl-url-2', name: 'Load Balancer', icon: 'split', category: 'Compute', x: 280, y: 130 },
      { id: 'tpl-url-3', name: 'Redirect Service', icon: 'box', category: 'Compute', x: 120, y: 250 },
      { id: 'tpl-url-4', name: 'Shortener API', icon: 'box', category: 'Compute', x: 440, y: 250 },
      { id: 'tpl-url-5', name: 'Cache (Redis)', icon: 'zap', category: 'Storage', x: 120, y: 370 },
      { id: 'tpl-url-6', name: 'SQL Database', icon: 'database', category: 'Storage', x: 320, y: 370 },
      { id: 'tpl-url-7', name: 'Rate Limiter', icon: 'shield', category: 'Observability', x: 520, y: 370 },
      { id: 'tpl-url-8', name: 'Metrics Collector', icon: 'bar-chart', category: 'Observability', x: 320, y: 480 },
    ],
    edges: [
      { id: 'tue-1', from: 'tpl-url-1', fromAnchor: 'bottom', to: 'tpl-url-2', toAnchor: 'top' },
      { id: 'tue-2', from: 'tpl-url-2', fromAnchor: 'bottom', to: 'tpl-url-3', toAnchor: 'top' },
      { id: 'tue-3', from: 'tpl-url-2', fromAnchor: 'bottom', to: 'tpl-url-4', toAnchor: 'top' },
      { id: 'tue-4', from: 'tpl-url-3', fromAnchor: 'bottom', to: 'tpl-url-5', toAnchor: 'top' },
      { id: 'tue-5', from: 'tpl-url-3', fromAnchor: 'bottom', to: 'tpl-url-6', toAnchor: 'top' },
      { id: 'tue-6', from: 'tpl-url-4', fromAnchor: 'bottom', to: 'tpl-url-6', toAnchor: 'top' },
      { id: 'tue-7', from: 'tpl-url-4', fromAnchor: 'bottom', to: 'tpl-url-7', toAnchor: 'top' },
      { id: 'tue-8', from: 'tpl-url-6', fromAnchor: 'bottom', to: 'tpl-url-8', toAnchor: 'top' },
    ],
  },
]
